name: rotating_dial_widget
description: A Flutter Widget package for rotating dial.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: